### ISSUE TITLE
Slowdowns when using DZ devices at 19200 baud

### ISSUE THREAD

**Issue by darkstar** [simh/simh#252]
I'm having some trouble with the emulated DZ devices on a VAX. The last testing was done with revision 109c197f from today.

I'm running Ultrix 4.5 on VAX, installed from the ISO image floating around the net. I have set up SimH with 16 DZ lines on telnet port 1005.

When I set the getty speed to 19200 baud on these lines (via /etc/ttys) and try to log in, I get various states of slowdown with the whole emulation (not just the DZ lines but also the main console is getting slow). The problem seems to be worse after closing the telnet windows, where it sometimes takes up to a minute for the main console (and the SimH window) to be responsive again. This issue does not manifest itself (at least not in such a strong way) when using 9600 baud on the DZ lines.

How to reproduce:

I have uploaded an image [here](https://mega.nz/#!0wd1gTIb!L9aVngw6mYqMOrUIBBpLmPb32gYHHRfHdZ-pinjbbqo) (~80 mb, 1.2gb uncompressed). Just run SimH with the included config file, boot from DUA0, and log in as root with password ultrix. Then connect to port 1005 and open a few serial windows and try to log in there as root. The slowdown should be noticeable (note that you will get an error message about a secure terminal, that's okay, it's not configured correctly yet). Also try to type something on the main console at the same time, sometimes you will get a few seconds of delay. Then, close the DZ sessions and with a bit of luck you get such a massive delay/hang that not even Ctrl-E in the SimH window will work. After a minute or so, everything is back to normal

**Comment by markpizz** [comment]
Thanks for opening this case.

Hmm...  I see what you mean.  Behavior is odd at least.

So, I ^E on the simulator session and type "SHOW MUX".

The output produces:

    Simulation stopped, PC: 800034F3 (MTPR #18,#12)
    sim> sh mux
    Multiplexer device: DZ, lines=16,
        attached to 1005, 1 current connection, sessions=1
    Line: 0, Speed=300 bps
    Connection from IP address ::1
    Connection [::1]:1005->[::1]:62192
     Connected 00:00:48
     Telnet protocol
      input (on) queued/total = 0/76
      output (on) queued/total = 0/192
      bytes in buffer = 192
    Line: 1, Speed=300 bps
    Line: 2, Speed=300 bps
    Line: 3, Speed=300 bps
    Line: 4, Speed=300 bps
    Line: 5, Speed=300 bps
    Line: 6, Speed=300 bps
    Line: 7, Speed=300 bps
    Line: 8
    Line: 9
    Line: 10
    Line: 11
    Line: 12
    Line: 13
    Line: 14
    Line: 15
    Multiplexer device: CON-TEL,
        attached to 1001, connected, sessions=1
    Connection from IP address ::1
    Connection [::1]:1001->[::1]:62137
     Connected 00:05:43
     Telnet protocol
      input (on) queued/total = 0/99
      output (on) queued/total = 0/3958
      bytes in buffer = 256
    sim>

Yet /etc/ttys contains:

    # @(#)ttys      9.1 (ULTRIX) 4/26/94
    #
    #
    #
    # name  getty           type            status          comments
    #
    console "/etc/getty std.9600" vt100     on secure       # console terminal
    tty00   "/etc/getty std.19200" vt100    on nomodem      # direct connect tty
    tty01   "/etc/getty std.19200" vt100    on nomodem      # direct connect tty
    tty02   "/etc/getty std.19200" vt100    on nomodem      # direct connect tty
    tty03   "/etc/getty std.19200" vt100    on nomodem      # direct connect tty
    tty04   "/etc/getty std.19200" vt100    on nomodem      # direct connect tty
    tty05   "/etc/getty std.19200" vt100    on nomodem      # direct connect tty
    tty06   "/etc/getty std.19200" vt100    on nomodem      # direct connect tty
    tty07   "/etc/getty std.19200" vt100    on nomodem      # direct connect tty
    ttyd0   "/etc/getty std.9600" vt100     off shared secure # modem line
    ttyp0   none            network
    ttyp1   none            network
    ttyp2   none            network
    ttyp3   none            network
    ttyp4   none            network
    ttyp5   none            network

This is odd.  It seems that there is some ambiguity programming the port speeds.  This is  the first test on Ultrix.  The VMS driver initializes all lines that it finds to 9600 during the initial driver startup.  I'll have to look for what is going on here, but the fact that some of these ended up at 300bps strongly suggests a programming issue?  Is there source code available for this or even earlier Ultrix versions?  The only reason I can't believe that someone was messing with the code to the DZ device driver would be due to the fact that the device registers on some of the other VAX systems (3100, etc) are programmatically similar to the DZ and on VMS actually use the DZ device driver for the VAXStation keyboard and mouse.

In any case, Ultrix seems to be mapping the desired 19200 speed to 300 or it doesn't like something about the format of /etc/ttys or the /etc/gettytab and is defaulting to 300?  Debug output of the values being passed into the DZ LPR expliclly show that the speed is being set to 300!  I'll leave digging into that up to you.

Meanwhile, there are several other behaviors that need be addressed here:
1) Idle doesn't seem to work very well on this OS.  There are OS specific IDLE settings since some idle patterns in one OS do occur in other OSes but don't indicate idling!  Things seem to work well with "SET CPU IDLE=ULTRIX".

2) The apparent hang which you are originally raising this issue about.  This is related to there be N DZ ports but only some of them have a specific speed setting and properly considering the input state of all lines.   I think the latest code fixes this,

**Comment by darkstar** [comment]
The source code for some Ultrix versions is available [here](https://archive.org/download/various_operating_system_source_code), however 4.5 is not among them. But maybe 4.2 and/or 4.3 are close enough. If I can find a binary distribution of 4.2 or 4.3 I could check the behavior there, but so far I only have 4.0 and 4.5 media.

**Comment by Rhialto** [comment]
On Tue 08 Dec 2015 at 17:10:16 -0800, Mark Pizzolato wrote:
> In any case, Ultrix seems to be mapping the desired 19200 speed to 300
> or it doesn't like something about the format of /etc/ttys or the
> /etc/gettytab and is defaulting to 300?  Debug output of the values
> being passed into the DZ LPR expliclly show that the speed is being
> set to 300!  I'll leave digging into that up to you.

This is a long shot (and I haven't looked at the actual file), but the
std.19200 in /etc/ttys is just an entry name in /etc/gettytab.

Normally it would look something like (this is one from NetBSD):

std.19200|19200-baud:\
        :sp#19200:

where sp#19200 indicates the actual speed setting. Theoretically
somebody might have changed that (although that would be very weird of
course). But something to check and rule out.

I just think of another more likely thing: could Ultrix be trying
auto-baud, starting at 300? The emulated serial lines are, I expect, so
perfect that they never have any framing errors at any speed, and never
trigger a speed change.

-Olaf.
-- 
___ Olaf 'Rhialto' Seibert  -- The Doctor: No, 'eureka' is Greek for
\X/ rhialto/at/xs4all.nl    -- 'this bath is too hot.'

**Comment by markpizz** [comment]
The massive slows downs and unresponsiveness was a bug, which I believe has been fixed.  Please convince yourself about this.  Also, please run with SET CPU IDLE=ULTRIX.

Meanwhile, @rhialto's  autobaud idea is a good theory.  Trying to drive all of this at arms length through getty is pretty complicated.

    sim> SET DEBUG stdout
    sim> SET DZ DEBUG=REG

Will display all of the accesses to the device registers.  Look for write activity to the LPR to see what the driver is sending.

It would seem that one could test some of this on ports which getty isn't touching with an 'stty -F /dev/otherport' command to get this away from getty.  I'll leave this to you.

**Comment by markpizz** [comment]
@darkstar. will you test the latest code and if the slowdowns and apparent hangs are fixed, please close the issue.

The fact that the OS is setting the port speed to 300 when the getty config says 19200 is, from my point of view, an OS "Feature" which is beyond anything which simh may be doing wrong.

**Comment by hbent** [comment]
Under Ultrix 4.5 with the latest git, everything is fine if my serial lines are all set to 9600 but if I set them to various speeds, I get interesting results:

`Multiplexer device: DZ, lines=8,`
`    attached to 4500, 0 current connections, sessions=0`
`Line: 0, Speed=300 bps`
`Line: 1, Speed=300 bps`
`Line: 2, Speed=4800 bps`
`Line: 3, Speed=300 bps`
`Line: 4, Speed=1200 bps`
`Line: 5, Speed=300 bps`
`Line: 6, Speed=300 bps`
`Line: 7, Speed=300 bps`

Those lines are set to 19200, 9600, 4800, 2400, 1200, 600, 300, and 110.  What's most surprising to me is that 9600 worked before but is not working now.

**Comment by hbent** [comment]
A cold reboot without exiting simh gave me all correct speeds, except for 19200 which is still showing as 300.  Mark, let me know what you need to diagnose this.

**Comment by markpizz** [comment]
Henry,

You can diagnose the simh side of things yourself with the above suggested debug output:

    sim> SET CONSOLE TELNET=1234
    sim> SET DEBUG stdout
    sim> SET DZ DEBUG=REG

Use a telnet session to get to the simulated system's console port and use the session running the simulator.to collect data about things the OS is doing to the DZ device.  Any attempts by the OS to program the speed of the DZ ports will be done by references to the LPR register:
Will display all of the accesses to the device registers.  Look for debug output containing dz_wr (write activity) AND LPR (the Line Parameter register) to see what the driver is sending.  For example:

    DBG(171949929)> DZ REG: dz_wr(PA=0x2000004F [TDR ], access=1, data=0x0) TBR=00 CHAR=00
    DBG(171949934)> DZ REG: dz_wr(PA=0x2000004A [LPR ], access=2, data=0x1E18) RCVE0 SPEED=9600 PARODD0 PARENB0 STOPBITS0 CHARSIZE=8 LINE=0x0
    DBG(171952230)> DZ REG: dz_rd(PA=0x20000048 [CSR ], access=0, data=0x4060) TRDY1 TIE0 SA0 SAE0 TLINE=0x0 RDONE1 RIE1 MSE0 MAINT0
    DBG(171952238)> DZ REG: dz_wr(PA=0x2000004F [TDR ], access=1, data=0x0) TBR=00 CHAR=00
    DBG(171952243)> DZ REG: dz_wr(PA=0x2000004A [LPR ], access=2, data=0x1E19) RCVE0 SPEED=9600 PARODD0 PARENB0 STOPBITS0 CHARSIZE=8 LINE=0x1
    DBG(171954552)> DZ REG: dz_rd(PA=0x20000048 [CSR ], access=0, data=0x4060) TRDY1 TIE0 SA0 SAE0 TLINE=0x0 RDONE1 RIE1 MSE0 MAINT0
    DBG(171954560)> DZ REG: dz_wr(PA=0x2000004F [TDR ], access=1, data=0x0) TBR=00 CHAR=00
    DBG(171954565)> DZ REG: dz_wr(PA=0x2000004A [LPR ], access=2, data=0x1E1A) RCVE0 SPEED=9600 PARODD0 PARENB0 STOPBITS0 CHARSIZE=8 LINE=0x2

The hardware (real or simulated) behaves only as the software (OS) commands it.  :-)

Mark

**Comment by hbent** [comment]
It looks like the dz driver in Ultrix theoretically supports 19200 but sometime between 2.0 and 4.2 added a check for supported speeds that (presumably inadvertently) dropped 19200 support.  The dz driver should report that it supports everything that the kernel supports except 38400 and 200, but it also reports that it does not support 19200.  I tested the same simh executable that I used for 4.5 with 2.0 and it correctly sets 19200.  So this is an Ultrix bug, and can be closed.

**Comment by hbent** [comment]
Oh and FWIW I was not able to reproduce the problem I had with some of the lines not being set to the correct speeds.  Not sure what was going on there but things seem fine now.

**Comment by markpizz** [comment]
Well, there is one speed encoded value (0xF), which if the UART hardware in the DZ11 and DZV11 supported 19200 would be used for that. Both the DZ11 and DZV11 docs say that value(0xF) is invalid.  

The driver probably was fixed to avoid setting the device in an invalid state. Since there is no way for the simulator to report an error when/if this happens and since it has to pick something, 19200/makes sense.  The VMS V5.5-2 driver will set the line to 19200 and the simulator just works.
