### ISSUE TITLE
sim_debug() drops/truncates characters on macOS

### ISSUE THREAD

**Issue by deltecent** [simh/simh#957]
sim_debug drops/truncates characters on macOS.

When using sim_debug to output a lot of information on macOS, characters are lost/truncated and/or not written to STDOUT. 
- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
```
sim> show version
Altair 8800 (Z80) simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        no Ethernet
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC Apple LLVM 12.0.0 (clang-1200.0.32.2)
        Simulator Compiled as C arch: x64 (Release Build) on Nov 10 2020 at 21:40:37
        Build Tool: simh-makefile
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx (Version 8.43 2019-02-23) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Darwin Patricks-iMac-2.deltec.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
        tar tool: bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.6
        curl tool: curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
        git commit id: 777875ff+uncommitted-changes
        git commit time: 2020-11-06T19:40:06-0800
```
- #### how you built the simulator or that you're using prebuilt binaries

```
% make altairz80
lib paths are: /usr/lib /opt/local/lib /usr/local/Cellar/gcc/9.3.0_1/lib /usr/local/Cellar/gettext/0.20.2_1/lib /usr/local/Cellar/gmp/6.2.0/lib /usr/local/Cellar/isl/0.22.1/lib /usr/local/Cellar/jpeg/9d/lib /usr/local/Cellar/libffi/3.3/lib /usr/local/Cellar/libidn2/2.3.0/lib /usr/local/Cellar/libmpc/1.1.0/lib /usr/local/Cellar/libpng/1.6.37/lib /usr/local/Cellar/libunistring/0.9.10/lib /usr/local/Cellar/llvm/11.0.0/lib /usr/local/Cellar/mpfr/4.0.2/lib /usr/local/Cellar/openssl@1.0/1.0.2t/lib /usr/local/Cellar/openssl@1.1/1.1.1g/lib /usr/local/Cellar/qt/5.15.1/lib /usr/local/Cellar/telnet/63/lib /usr/local/Cellar/wget/1.20.3_2/lib /usr/local/Cellar/wimlib/1.13.2/lib /usr/X11/lib
include paths are:  /usr/local/include /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include /opt/local/include /usr/local/Cellar/gcc/9.3.0_1/include /usr/local/Cellar/gettext/0.20.2_1/include /usr/local/Cellar/gmp/6.2.0/include /usr/local/Cellar/isl/0.22.1/include /usr/local/Cellar/jpeg/9d/include /usr/local/Cellar/libffi/3.3/include /usr/local/Cellar/libidn2/2.3.0/include /usr/lousing libpthread: /usr/lib/libpthread.dylib /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread.h
using libpcre: /usr/lib/libpcre.dylib /opt/local/include/pcre.h
using libdl: /usr/lib/libdl.dylib /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/dlfcn.h
using libpng: /opt/local/lib/libpng.dylib /usr/local/include/png.h
using zlib: /usr/lib/libz.dylib /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/zlib.h
using mman: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/mman.h
***
*** altairz80 Simulator being built with:
*** - compiler optimizations and no debugging support. Apple clang version 12.0.0.
*** - Per simulator tests will be run.
***
*** git commit id is 777875ff52ce29b445f5004405a8f4136573d8b2+uncommitted-changes.
*** git commit time is 2020-11-06T19:40:06-0800.
***
gcc -std=c99 -U__STRICT_ANSI__  -O2 -fno-strict-overflow -finline-functions -DSIM_GIT_COMMIT_ID=777875ff52ce29b445f5004405a8f4136573d8b2+uncommitted-changes -DSIM_GIT_COMMIT_TIME=2020-11-06T19:40:06-0800  -DSIM_COMPILER="Apple clang version 12.0.0" -DSIM_BUILD_TOOL=simh-makefile -I . -D_GNU_SOURCE -I/opt/local/include -DUSE_READER_THREAD -DSIM_ASYNCH_IO  -DHAVE_PCRE_H -DHAVE_SYS_IOCTL -DHAVE_DLOPEN=dylib -DHAVE_UTIME -DHAVE_LIBPNG -DHAVE_ZLIB -DHAVE_GLOB -DHAVE_SHM_OPEN  ./AltairZ80/altairz80_cpu.c ./AltairZ80/altairz80_cpu_nommu.c ./AltairZ80/altairz80_dsk.c ./AltairZ80/disasm.c ./AltairZ80/altairz80_sio.c ./AltairZ80/altairz80_sys.c ./AltairZ80/altairz80_hdsk.c ./AltairZ80/altairz80_net.c ./AltairZ80/s100_hayes.c ./AltairZ80/s100_2sio.c ./AltairZ80/s100_pmmi.c ./AltairZ80/flashwriter2.c ./AltairZ80/i86_decode.c ./AltairZ80/i86_ops.c ./AltairZ80/i86_prim_ops.c ./AltairZ80/i8272.c ./AltairZ80/insnsd.c ./AltairZ80/altairz80_mhdsk.c ./AltairZ80/mfdc.c ./AltairZ80/n8vem.c ./AltairZ80/vfdhd.c ./AltairZ80/s100_disk1a.c ./AltairZ80/s100_disk2.c ./AltairZ80/s100_disk3.c ./AltairZ80/s100_fif.c ./AltairZ80/s100_mdriveh.c ./AltairZ80/s100_icom.c ./AltairZ80/s100_jadedd.c ./AltairZ80/s100_mdsa.c ./AltairZ80/s100_mdsad.c ./AltairZ80/s100_selchan.c ./AltairZ80/s100_ss1.c ./AltairZ80/s100_64fdc.c ./AltairZ80/s100_scp300f.c ./AltairZ80/s100_tarbell.c ./AltairZ80/wd179x.c ./AltairZ80/s100_hdc1001.c ./AltairZ80/s100_if3.c ./AltairZ80/s100_adcs6.c ./AltairZ80/m68kcpu.c ./AltairZ80/m68kdasm.c ./AltairZ80/m68kasm.c ./AltairZ80/m68kopac.c ./AltairZ80/m68kopdm.c ./AltairZ80/m68kopnz.c ./AltairZ80/m68kops.c ./AltairZ80/m68ksim.c ./scp.c ./sim_console.c ./sim_fio.c ./sim_timer.c ./sim_sock.c ./sim_tmxr.c ./sim_ether.c ./sim_tape.c ./sim_disk.c ./sim_serial.c ./sim_video.c ./sim_imd.c ./sim_card.c -I ./AltairZ80 -DUSE_SIM_IMD -o BIN/altairz80 -L/opt/local/lib -L/usr/X11/lib -lm -lpthread -lpcre -ldl -lpng -lz  
BIN/altairz80 RegisterSanityCheck  </dev/null 
 Running internal register sanity checks on Altair 8800 (Z80) simulator.
*** Good Registers in Altair 8800 (Z80) simulator.
```
- #### the simulator configuration file (or commands) which were used when the problem occurred.

```
set debug stdout

set SIMH DEBUG=IN;OUT;CMD;VERBOSE;BUFFEREMPTY

dep 0000 3e
dep 0001 06
dep 0002 d3
dep 0003 fe
dep 0004 db
dep 0005 fe
dep 0006 c3
dep 0007 00
dep 0008 00

g 0

#0000:         		ORG 0000H
#              	
#0000:         	LOOP
#0000: 3E06    		MVI	A,006H
#0002: D3FE    		OUT	0FEH
#0004: DBFE    		IN	0FEH
#0006: C30000  		JMP	LOOP

```
- #### the expected behavior and the actual behavior

```
DBG(37418)> SIMH CMD: SIMH: [0x00000002] CMD(0xfe) <- 6 (0x06, 'getSIMHVersion')
DBG(37419)> SIMH IN: SIMH: [0x00000004] IN(0xfe) -> 83 (0x53, 'S')
DBG(37422)> SIMH OUT: SIMH: [0x00000002] OUT(0xfe) <- 6 (0x06, '?')
DBG(37422)> SIMH CMD: SIMH: [0x00000002] CMD(0xfe) <- 6 (0x06, 'getSIMHVersion')
DBG(37423)> SIMH IN: SIMH: [0x00000004] IN(0xfe) -> 83 (0x53, 'S')DBG(37454)> SIMH CMD: SIMH: [0x00000002] CMD(0xfe) <- 6 (0x06, 'getSIMHVersion')
DBG(37455)> SIMH IN: SIMH: [0x00000004] IN(0xfe) -> 83 (0x53, 'S')
DBG(37458)> SIMH OUT: SIMH: [0x00000002] OUT(0xfe) <- 6 (0x06, '?')
DBG(37458)> SIMH CMD: SIMH: [0x00000002] CMD(0xfe) <- 6 (0x06, 'getSIMHVersion')
DBG(37459)> SIMH IN: SIMH: [0x00000004] IN(0xfe) -> 83 (0x53, 'S')
DBG(37462)> SIMH OUT: SIMH: [0x00000002] OUT(0xfe) <- 6 (0x06, '?')
DBG(37462)> SIMH CMD: SIMH: [0x00000002] CMD(0xfe) <- 6 (0x06, 'getSIMHVersion')
DBG(37463)> SIMH IN: SIMH: [0x00000004] IN(0xfe) -> 83 (0x53, 'S')
DBG(37466)> SIMH OUT: SIMH: [0x00000002] OUT(0xfe) <- 6 (0x06, '?')
DBG(37466)> SIMH CMD: SIMH: [0x00000002] CMD(0xfe) <- 6 (0x06, 'getSIMHVersion')
DBG(37467)> SIMH IN: SIMH: [0x00000004] IN(0xfe) -> 83 (0x53, 'S')
DBG(37470)> SIMH OUT: SIMH: [0x00000002] OUT(0xfe) <- 6 (0x06, '?')
DBG(37470)> SIMH CMD: SIMH: [0x00000002] CMD(0xfe) <- 6 (0x06, 'getSIMHVersion')
DBG(37471)> SIMH IN: SIMH: [0x00000004] IN(0xfe) -> 83 (0x53, 'S')DBG(37478)> SIMH OUT: SIMH: [0x00000002] OUT(0xfe) <- 6 (0x06, '?')
DBG(37478)> SIMH CMD: SIMH: [0x00000002] CMD(0xfe) <- 6 (0x06, 'getSIMHVersion')
DBG(37479)> SIMH IN: SIMH: [0x00000004] IN(0xfe) -> 83 (0x53, 'S')
DBG(37482)> SIMH OUT: SIMH: [0x00000002] OUT(0xfe) <- 6 (0x06, '?')
DBG(37482)> SIMH CMD: SIMH: [0x00000002] CMD(0xfe) <- 6 (0x06, 'getSIMHVersion')
DBG(37483)> SIMH IN: SIMH: [0x00000004] IN(0xfe) -> 83 (0x53, 'S')
DBG(37486)> SIMH OUT: SIMH: [0x00000002] OUT(0xfe) <- 6 (0x06, '?')
DBG(37486)> SIMH CMD: SIMH: [0x00000002] CMD(0xfe) <- 6 (0x06, 'getSIMHVersion')
DBG(37487)> SIMH IN: SIMH: [0x00000004] IN(0xfe) -> 83 (0x53, 'S')
DBG(37490)> SIMH OUT: SIMH: [0x00000002] OUT(0xfe) <- 6 (0x06, '?')
DBG(37490)> SIMH CMD: SIMH: [0x00000002] CMD(0xfe) <- 6 (0x06, 'getSIMHVersion')
DBG(37491)> SIMH IN: SIMH: [0x00000004] IN(0xfe) -> 83 (0x53, 'S')
DBG(37494)> SIMH OUT: SIMH: [0x00000002] OUT(0xfe) <- 6 (0x06, '?')
DBG(37494)> SIMH CMD: SIMH: [0x00000002] CMD(0xfe) <- 6 (0x06, 'getSIMHVersion'DBG(37511)> SIMH IN: SIMH: [0x00000004] IN(0xfe) -> 83 (0x53, 'S')
DBG(37514)> SIMH OUT: SIMH: [0x00000002] OUT(0xfe) <- 6 (0x06, '?')
```
This is another example running `3812DIAG.ASM` and the `ICOM` device:
```
DBG(1828347)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 formatMode=FALSE
DBG(1828354)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 formatMode=FALSE
DBG(1828361)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 formatMode=FALSE
DBG(1828368)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 formatMode=FALSE
DBG(1828375)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 foDBG(1828487)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 formatMode=FALSE
DBG(1828494)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 formatMode=FALSE
DBG(1828501)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 formatMode=FALSE
DBG(1828508)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 formatMode=FALSE
DBG(1828515)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 formatMode=FALSE
DBG(1828522)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 formatMode=FALSE
DBG(1828529)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 formatMode=FALSE
DBG(1828536)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 formatMode=FALSE
DBG(1828543)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 formatMode=FALSE
DBG(1828550)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 formatMode=FALSE
DBG(1828557)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 formatMode=FALSE
DBG(1828564)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 formatMode=FALSE
DBG(1828571)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 formatMode=FALSE
DBG(1828578)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 formatMode=FALSE
DBG(1828585)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 formatMode=FALSE
DBG(1828592)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 foDBG(1828760)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 formatMode=FALSE
DBG(1828767)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 formatMode=FALSE
DBG(1828774)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 formatMode=FALSE
DBG(1828781)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 formatMode=FALSE
DBG(1828788)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=03 stat=40h density=128 formatMode=FALSE

DBG(3647324)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=24 stat=40h density=128 formatMode=FALSE
DBG(3647331)> DBG(3647541)> ICOM WBUF: LOAD WRITE BUF 51=18
DBG(3647541)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=24 stat=40h density=128 formatMode=FALSE

DBG(3799153)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=04 stat=40h density=128 formatMode=FALSE
DBG(3799160)> ICOM WBUF: LOAD WRITE BUF 3=04
DBG(3799160)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=0DBG(3799209)> ICOM WBUF: LOAD WRITE BUF 10=00
DBG(3799209)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=04 stat=40h density=128 formatMode=FALSE
DBG(3799216)> ICOM WBUF: LOAD WRITE BUF 11=04

DBG(3800014)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=04 stat=40h density=128 formatMode=FALSE
DBG(3800021)> ICOM WBUF: LOAD WRITE BUF 126=00
DBG(3800021)> ICOM CMD: LD WR BUF     (31h) unit=0 trk=00 sec=04 stat=40h density=128 formatMode=FALSE
DBG(3800DBG(3800038)> ICOM WRITE: wrote 128 bytes at offset 0180
DBG(3800038)> ICOM WRDETAIL: wdata unit 0 track/sector 00/04:
DBG(3800038)> ICOM WRDETAIL: 	00 04 00 04 00 04 00 04 00 04 00 04 00 04 00 04 
DBG(3800038)> ICOM WRDETAIL: 	00 04 00 04 00 04 00 04 00 04 00 04 00 04 00 04 


```
- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
It is not obvious to me what you expect vs what you are getting and something specific about the loss of debug output.

The only "loss of debug output" that is "normal" is the fact that, by default, sim_debug() defers emitting a line of debug output until it is presented with another line of debug output.  This deferral exists to so that multiple lines of successive debug output can be summarized with "same as above (nnn times)" which, depending what you're doing can reduce the size of the debug output produced dramatically with no  useful loss of information.  Sometimes you may absolutely want to see every line of debug output immediately as it is produced.  That can be enabled by using the -F switch on the "SET DEBUG -F debug-destination" command.

Ahh.  I see the lines of output that do seem to be missing some stuff (only on macOS as it turns out).

This only seems to happen with output being written to STDOUT.  If you send your DEBUG output to a file, I don't see any of this truncation.

In any case I don't see an obvious solution to this problem.  The debug data being written by SCP is written in _debug_fwrite().  I changed the two calls to fwrite() in that routine to check the return value from fwrite() and to loop and write any unwritten data of the data if it all wasn't written.  That change had no effect on the observed problem.  

I'm open to suggestions about how to solve this when the debug output is going to STDOUT.

**Comment by deltecent** [comment]
It wasn't obvious to me either or I would have sent in a PR through Peter.

FYI, it also does this when going to STDERR:

```
DBG(266867)> SIMH IN: SIMH: [0x00000004] IN(0xfe) -> 83 (0x53, 'S')
DBG(266870)> SIMH OUT: SIMH: [0x00000002] OUT(0xfe) <- 6 (0x06, '?'DBG(266895)> SIMH IN: SIMH: [0x00000004] IN(0xfe) -> 83 (0x53, 'S')
DBG(266898)> SIMH OUT: SIMH: [0x00000002] OUT(0xfe) <- 6 (0x06, '?')
```
It also happens with the "-F" debug flag. That may be easier to debug.

**Comment by markpizz** [comment]
This issue is a general SCP one and not AltairZ80 specific.  Since you've provided a simple demonstration of the problem, any fix you suggest doesn't have to route through Peter, but it could if you want.

As for it also affecting STDERR, surely that is the case since under the covers they are both connected to the console session.  I suspect that if either STDERR or STDOUT were connected to a file (done external to the simulator), the problem would also not appear.

I am not an Xcode user, and gdb doesn't work out of the box after installing the latest Xcode, so I leave debugging this to someone more familiar with working on the macOS platform.

BTW, building the simulator with "make simulator-name DEBUG=1" will produce one compiled with debug support.  From my experience, debuggers (gdb at least) catch SIGINT and it isn't clear if or how it may or may not get passed into the process being debugged.  On macOS and Linux, the simulator's detection of the WRU character (usually ^E) is delivered via SIGINT so we have a potential problem getting back to the sim> prompt when using a host platform debugger.  To address this, on macOS and Linux, when a simulator is compiled with DEBUG=1, it actually detects the WRU character by console polling (instead of SIGINT delivery) and the poll actually uses the set value of the WRU character PLUS 1.  Hence with a default setup, ^F will get you back to the sim> prompt.

**Comment by deltecent** [comment]
```
DBG(361)> SIMH CMD: SIMH: [0x00000002] CMD(0xfe) <- 6 (0x06, 'getSIMHVersion')
*errno=35, err_msg="Resource temporarily unavailable" fcntl=0006 O_NONBLOCK=0004
DBG(362)> SIMH IN: SIMH: [0x00000004] IN(0xfe) -> 83 (0x53, 'S')
```
`stdout` and `stderr` are non-blocking and data is being written using `fwrite` faster than it can be output to the console. The reason for this is on macOS (and maybe others) `stdin`, `stdout`, and `stderr` point to the same file description. When stdin is changed to non-blocking in `sim_os_ttrun`, that also sets `stdout` and `stderr` to non-blocking.

This was recreated with the following program:

```
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <fcntl.h>
#include <sys/errno.h>
#include <string.h>

int main(void);

int main()
{
	int flags;
	int serrno;

	flags = fcntl(fileno(stdin), F_GETFL, 0);
	printf("stdin  fd=%d flags=%04x\n", fileno(stdin), flags);

	flags = fcntl(fileno(stdout), F_GETFL, 0);
	printf("stdout fd=%d flags=%04x\n", fileno(stdout), flags);

	flags = fcntl(fileno(stderr), F_GETFL, 0);
	printf("stderr fd=%d flags=%04x\n", fileno(stderr), flags);

	printf("stdin O_NONBLOCK\n");

	fcntl(fileno(stdin), F_SETFL, flags | O_NONBLOCK);                  /* non-block mode */

	flags = fcntl(fileno(stdin), F_GETFL, 0);
	printf("stdin  fd=%d flags=%04x\n", fileno(stdin), flags);

	flags = fcntl(fileno(stdout), F_GETFL, 0);
	printf("stdout fd=%d flags=%04x\n", fileno(stdout), flags);

	flags = fcntl(fileno(stderr), F_GETFL, 0);
	printf("stderr fd=%d flags=%04x\n", fileno(stderr), flags);

        errno = 0;

	while (!errno) {
		fprintf(stdout, "(123456) ");
		fwrite("0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789\r\n", 1, 102, stdout);
		printf("(654321) ");
		fwrite("01234567890123456789012345678901234567890123456789\r\n", 1, 52, stdout);
	}

	serrno = errno;

	sleep(1);

        printf("*errno=%d, err_msg=\"%s\"\r\n", serrno, strerror(serrno));

	fcntl (fileno(stdin), F_SETFL, flags);                  /* non-block mode */
}
```
```
% ./stdout
stdin  fd=0 flags=0002
stdout fd=1 flags=0002
stderr fd=2 flags=0002
stdin O_NONBLOCK
stdin  fd=0 flags=0006
stdout fd=1 flags=0006
stderr fd=2 flags=0006
(123456) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(654321) 01234567890123456789012345678901234567890123456789
(123456) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(654321) 01234567890123456789012345678901234567890123456789
(123456) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(654321) 01234567890123456789012345678901234567890123456789
(123456) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(654321) 01234567890123456789012345678901234567890123456789
(123456) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(654321) 01234567890123456789012345678901234567890123456789
(123456) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(654321) 01234567890123456789012345678901234567890123456789
(123456) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(654321) 01234567890123456789012345678901234567890123456789
(123456) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(654321) 01234567890123456789012345678901234567890123456789
(123456) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(654321) 01234567890123456789012345678901234567890123456789
(123456) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(654321) 01234567890123456789012345678901234567890123456789
(123456) 01234567890123456789012345678901234567890123456789012345678901234567890123456789012*errno=35, err_msg="Resource temporarily unavailable"
```

**Comment by deltecent** [comment]
Rather than setting `stdin` to non-blocking, SIMH should probably use `select` to check `stdin` for input.

**Comment by markpizz** [comment]
Even with a non blocking file descriptor, a write that can't complete should return how much actually was written and what I wrote to retry it (based on the return value of fwrite) should have retried until all was written.  That this did nothing different suggests that fwrite on macOS doesn't return the count of bytes written successfully.

It is a good thing that writes to sockets reliably return what was written.

**Comment by markpizz** [comment]
I wrote that last comment on my phone where I really couldn't read all of your test program.  I also won't be near my macOS test system for 3-4 days, so please change your test program to:
1) remove the second printf and fwrite in the while (!errno) loop and save the return value from the fwrite()
2) combine the printf and fwrite output to a single call to fwrite increasing the fwrite count value to 111.
3) add the saved fwrite return value to the printf output where serrno is displayed.

In a correctly behaving fwrite implementation, the fwrite return value should be between 0 and 110 when errno is non-zero.

**Comment by deltecent** [comment]
The behavior is absolutely bizarre. With the `sleep(1)` before the `printf`, the output pauses for one second about halfway through the last line, then the rest of the line shows up with the `printf` output:
```
stdin  fd=0 flags=0002
stdout fd=1 flags=0002
stderr fd=2 flags=0002
stdin O_NONBLOCK
stdin  fd=0 flags=0006
stdout fd=1 flags=0006
stderr fd=2 flags=0006
(0001) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(0002) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(0003) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(0004) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(0005) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(0006) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(0007) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(0008) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(0009) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(0010) 012345678901234567890123456[1 second sleep]7890123456789012345678901234567890123456789012345678901234567890123456789
bytes=0, lines=10, *errno=35, err_msg="Resource temporarily unavailable"
```

If I remove the `sleep(1)`, I get the following:
```
(0001) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(0002) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(0003) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(0004) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(0005) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(0006) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(0007) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(0008) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(0009) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(0010) 012345678901234567890123456% 
```
It appears that although it is returning 0, and errno is being set, it has actually buffered the entire line (somewhere) and if it's given some time, it will display them all. So far this is meeting the definition of "broke".
```
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <fcntl.h>
#include <sys/errno.h>
#include <string.h>

int main(void);

int main()
{
	int flags;
	int serrno;
	int bytes;
	int lines = 0;
	char string[128];

	flags = fcntl(fileno(stdin), F_GETFL, 0);
	printf("stdin  fd=%d flags=%04x\n", fileno(stdin), flags);

	flags = fcntl(fileno(stdout), F_GETFL, 0);
	printf("stdout fd=%d flags=%04x\n", fileno(stdout), flags);

	flags = fcntl(fileno(stderr), F_GETFL, 0);
	printf("stderr fd=%d flags=%04x\n", fileno(stderr), flags);

	printf("stdin O_NONBLOCK\n");

	fcntl(fileno(stdin), F_SETFL, flags | O_NONBLOCK);                  /* non-block mode */

	flags = fcntl(fileno(stdin), F_GETFL, 0);
	printf("stdin  fd=%d flags=%04x\n", fileno(stdin), flags);

	flags = fcntl(fileno(stdout), F_GETFL, 0);
	printf("stdout fd=%d flags=%04x\n", fileno(stdout), flags);

	flags = fcntl(fileno(stderr), F_GETFL, 0);
	printf("stderr fd=%d flags=%04x\n", fileno(stderr), flags);

        errno = 0;

	while (!errno) {
		lines++;
		sprintf(string, "(%04d) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789\r\n", lines);
		bytes = fwrite(string, 1, strlen(string), stdout);
	}

	serrno = errno;

	sleep(1);

        printf("bytes=%d, lines=%d, *errno=%d, err_msg=\"%s\"\r\n", bytes, lines, serrno, strerror(serrno));
}

```

**Comment by markpizz** [comment]
This includes the logic I had tried in sim_debug:

#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <fcntl.h>
#include <sys/errno.h>
#include <string.h>

int main(void);

static size_t written;

void fwrite_it (const char *buf, size_t len, FILE *f)
{
while (len > 0) {
    written = fwrite (buf, 1, len, f);
    len -= written;
    buf += written;
    }
}

int main()
{
	int flags;
	int serrno;
	int lines = 0;
	char string[128];

	flags = fcntl(fileno(stdin), F_GETFL, 0);
	printf("stdin  fd=%d flags=%04x\n", fileno(stdin), flags);

	flags = fcntl(fileno(stdout), F_GETFL, 0);
	printf("stdout fd=%d flags=%04x\n", fileno(stdout), flags);

	flags = fcntl(fileno(stderr), F_GETFL, 0);
	printf("stderr fd=%d flags=%04x\n", fileno(stderr), flags);

	printf("stdin O_NONBLOCK\n");

	fcntl(fileno(stdin), F_SETFL, flags | O_NONBLOCK);                  /* non-block mode */

	flags = fcntl(fileno(stdin), F_GETFL, 0);
	printf("stdin  fd=%d flags=%04x\n", fileno(stdin), flags);

	flags = fcntl(fileno(stdout), F_GETFL, 0);
	printf("stdout fd=%d flags=%04x\n", fileno(stdout), flags);

	flags = fcntl(fileno(stderr), F_GETFL, 0);
	printf("stderr fd=%d flags=%04x\n", fileno(stderr), flags);

        errno = 0;

	while (!errno) {
		lines++;
		sprintf(string, "(%04d) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789\r\n", lines);
               fwrite_it (string, strlen(string), stdout);
	}

	serrno = errno;

	sleep(1);

        printf("bytes=%d, lines=%d, *errno=%d, err_msg=\"%s\"\r\n", (int)written, lines, serrno, strerror(serrno));
}

**Comment by deltecent** [comment]
I already maintain a custom version of SIMH to get around timing problems caused by TMXR. I'll make it so stdin/stdout/stderr don't run in nonblocked mode which will fix the problem.

**Comment by deltecent** [comment]
I think this may actually be an easy fix. It looks like there's a version of `sim_os_poll_kbd_ready` that already uses `select`, which is the correct way to do it, not O_NONBLOCK. I assume this version is for *NIX-based operating systems, like macOS.

```
static t_bool sim_os_poll_kbd_ready (int ms_timeout)
{
fd_set readfds;
struct timeval timeout;

if (!isatty (0)) {                           /* skip if !tty */
    sim_os_ms_sleep (ms_timeout);
    return FALSE;
    }
FD_ZERO (&readfds);
FD_SET (0, &readfds);
timeout.tv_sec = (ms_timeout*1000)/1000000;
timeout.tv_usec = (ms_timeout*1000)%1000000;
return (1 == select (1, &readfds, NULL, NULL, &timeout));
}
```

**Comment by markpizz** [comment]
> I already maintain a custom version of SIMH to get around timing problems caused by TMXR. I'll make it so stdin/stdout/stderr don't run in nonblocked mode which will fix the problem.  That will be much easier than getting Apple to fix stdio.

The demonstration program here is simple enough to be useful in a direct bug report.  You should push that one along in any case.  Sure, while waiting for a real fix from apple, work around your problem temporarily with a blocking I/O approach (as mentioned in either of your last two comments), but that isn't an appropriate solution for simh since blocking output will create other timing issues in simh.  The sim_os_poll_kbd_ready () code exists to be used when TMXR activities use async mux activities which never has been fully debugged.  That approach intended to do all I/O to mux devices in separate threads which indeed blocked waiting for data ready.  The point of this approach, was to avoid primary path simulator code actually doing any system calls while polling for input or output complete,  Rather than them polling threads doing the select calls (blocking) would wait for specific I/O availability and then enable execution of the units that needed to wake up for data.

I managed to get into my macOS test system remotely.  I tried the below test program.  It never exits, but the output that it produces is absolutely not correct.  I thought this approach might be a possible work around to the C runtime being broken, I tried changed the fwrite to call the write system call, and the problem is clearly there and not in the C runtime,  This behavior directly violates the apple supplied documentation for the write system call clearly spelled out here: 
https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/write.2.html
Below the demo program is a cut and paste of a section of the output that is wrong.
```
#include <unistd.h>
#include <stdio.h>
#include <fcntl.h>
#include <sys/errno.h>
#include <string.h>

int main(void);

ssize_t written;

void fwrite_it (const char *buf, size_t len, FILE *f)
{
    int fd = fileno(f);

    while (len > 0) {
        written = write ifd, buf len)
//      written = fwrite (buf, 1, len, f);
	if (writen >= 0) {
            len -= written;
            buf += written;
            }
        errno = 0;
    }
}

int main()
{
	int flags;
	int serrno;
	int bytes;
	int lines = 0;
	char string[128];

	flags = fcntl(fileno(stdin), F_GETFL, 0);
	printf("stdin  fd=%d flags=%04x\n", fileno(stdin), flags);

	flags = fcntl(fileno(stdout), F_GETFL, 0);
	printf("stdout fd=%d flags=%04x\n", fileno(stdout), flags);

	flags = fcntl(fileno(stderr), F_GETFL, 0);
	printf("stderr fd=%d flags=%04x\n", fileno(stderr), flags);

	printf("stdin O_NONBLOCK\n");

	fcntl(fileno(stdin), F_SETFL, flags | O_NONBLOCK);                  /* non-block mode */

	flags = fcntl(fileno(stdin), F_GETFL, 0);
	printf("stdin  fd=%d flags=%04x\n", fileno(stdin), flags);

	flags = fcntl(fileno(stdout), F_GETFL, 0);
	printf("stdout fd=%d flags=%04x\n", fileno(stdout), flags);

	flags = fcntl(fileno(stderr), F_GETFL, 0);
	printf("stderr fd=%d flags=%04x\n", fileno(stderr), flags);

        errno = 0;

	while (!errno) {
		lines++;
		sprintf(string, "(%04d) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789\r\n", lines);
               fwrite_it (string, strlen(string), stdout);
	}

	serrno = errno;

	sleep(1);

        printf("bytes=%d, lines=%d, *errno=%d, err_msg=\"%s\"\r\n", (int)written, lines, serrno, strerror(serrno));
}
```
```
(178046) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178047) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178048) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178049) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178050) 012345678901234567890123456789012345678(178050) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178051) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178052) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178053) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178054) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178055) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178056) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178057) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178058) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178059) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178060) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178061) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178062) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178063) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178064) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178065) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178066) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178067) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178068) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178069) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178070) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178071) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178072) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178073) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178074) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178075) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178076) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178077) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178078) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178079) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178080) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178081) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178082) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178083) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178084) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178085) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178086) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178087) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178088) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178089) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178090) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178091) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178092) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178093) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178094) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178095) 01234567890123456789012345678901234567890123456789012345678901234567890(178095) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178096) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178097) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178098) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178099) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178100) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178101) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178102) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178103) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178104) 0123456(178104) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178105) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
(178106) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
```

That is a real macOS bug, but for all practical reasons, it needn't negatively affect normal simulator operation.  It certainly is a factor with your debug use case, but I've found that pushing that much debug data to simh's STDOUT or STDERR isn't particularly useful.  That much data is best leveraged when written to a file, stoppiig the simulator and digging through the file.

**Comment by psco** [comment]
After fixing the typos I ran the above program (the version with "write" not "fwrite") on the latest macOS Catalina (macOS 10.15.7 (19H15)) and let it produce two million lines of output, all fine. So I am not yet convinced that there is a macOS bug. Actually the use of "write" instead of "fwrite" might open up a route to fix the problem as error handling for "write" appears to be possible while for "fwrite" I do not see a reliable way once a problem has occurred.

Also note that Patrick's original test program will also stop on Ubuntu 20.10 with the message (in my case):
bytes=109, lines=160, *errno=11, err_msg="Resource temporarily unavailable"
This means that the issue when lots of debug data is written to stdout will most likely happen there as well. Of course I fully agree with your suggestion to dump this much data to a file and take it from there.

**Comment by deltecent** [comment]
The bottom line is doing non-blocking writes without any sort of error checking is asking for trouble, macOS not withstanding. I have not checked any other operating systems, but it seems very common for stdin/stdout/stderr to all point to the same file description, which is probably why Peter has also seen this on Ubuntu. Using non-blocking reads to get around using `select` is poor/lazy programming. There should be no reason to make stdin non-blocking when we have `select`.

I think one issue here is we're writing to a console. The fact is any fwrite to stdout/stderr that requires a block should not have any significant impact on timing (checking `fwrite` return code for actual bytes written and re-sending would have the same impact). We're not writing to a TCP/IP socket where delays could be lengthy, we're writing to a tty device. And I also don't understand the importance of timing issues. I can issue a `sim_activate_after_abs(uptr, 25000)` and my _svc routine will be dispatched in 0ms, or 15ms, or 1000ms. Sometimes it doesn't get dispatched at all, at least on the AltairZ80 simulator running a 2MHz clock speed. `sim_activate_after_abs` has been worthless for any sort of timing. The situation is compounded when TMXR tries to simulate a baud rate, even when using a serial port which is self-limited by is own physical baud rate (does TMXR need to simulate 9600bps when my serial port is set to 9600bps).

Also, the write function call is different on macOS too. It returns a -1 rather than the number of bytes written, which is probably why `fwrite` is returning 0, as it's getting a -1 return value from `write`.

From the macOS man page for fwrite:

>If an error occurs, or the end-of-file is reached, the return value is a short object count **(or zero)**.

It could be that Apple is saying, "If you are writing to a tty device in non-blocking mode, running out of buffer space is an error and we're going to return 0, so don't do that." I suspect the "Resource not available" **error** is coming all the way back from the tty device. Probably the same on Ubuntu.

I opened a topic on Apple's developer discussion board... but I wouldn't hold my breath.

>Of course I fully agree with your suggestion to dump this much data to a file and take it from there.

It isn't the amount of data that's the issue, it's how frequently `fwrite` is called. At least on MacOS, this can fail in as few as 10 lines. A burst of 20 lines of debug output to catch some specific event might fail. So send debug output to a file and `tail -f` to find out when it actually happens... Since this problem goes to the heart of SIMH's console input/output system, I suspect this will be the recommended work-around.

At this point, turning off O_NONBLOCK before the fwrite call and restoring to the previous flag's state after the call fixes my immediate problem until I have more time to fix SIMH's input/output system.

**Comment by deltecent** [comment]
Turns out `tail -f debug.log` doesn't work either.

**Comment by deltecent** [comment]
Right now sim_console.c has `if defined` code blocks for:

VMS
_WIN32
__OS2__
__MWERKS__ and macintosh
BSDTTY

And then the `#else` "POSIX" catch-all, which is where __APPLE__ is currently falling into.

My recommendation is to either fix the POSIX code block to work right without O_NONBLOCK (as all POSIX systems should be able to do this) or create yet another `if defined` code block for __APPLE__ that will eliminate the need of O_NONBLOCK on stdin/stdout/stderr.

**Comment by deltecent** [comment]
This needs more testing but seems to fix the output problem on the Mac and since it's in is own block, shouldn't impact any other systems:

```
/* macOS routines, from Patrick Linstruth */

#elif defined (__APPLE__)

#include <termios.h>
#include <unistd.h>

struct termios cmdtty,runtty;

static t_stat sim_os_ttinit (void)
{
sim_debug (DBG_TRC, &sim_con_telnet, "sim_os_ttinit() (__APPLE__)\n");

if (!isatty (STDIN_FILENO))                           /* skip if !tty */
    return SCPE_OK;
if (tcgetattr (STDIN_FILENO, &cmdtty) < 0)                         /* get old flags */
    return SCPE_TTIERR;
runtty = cmdtty;
runtty.c_lflag = runtty.c_lflag & ~(ECHO | ICANON);     /* no echo or edit */
runtty.c_oflag = runtty.c_oflag & ~OPOST;               /* no output edit */
runtty.c_iflag = runtty.c_iflag & ~ICRNL;               /* no cr conversion */
runtty.c_cc[VINTR] = sim_int_char;                      /* interrupt */
runtty.c_cc[VQUIT] = 0;                                 /* no quit */
runtty.c_cc[VERASE] = 0;
runtty.c_cc[VKILL] = 0;
runtty.c_cc[VEOF] = 0;
runtty.c_cc[VEOL] = 0;
runtty.c_cc[VSTART] = 0;                                /* no host sync */
runtty.c_cc[VSUSP] = 0;
runtty.c_cc[VSTOP] = 0;
runtty.c_cc[VMIN] = 0;                                  /* no waiting */
runtty.c_cc[VTIME] = 0;
return SCPE_OK;
}

static t_stat sim_os_ttrun (void)
{
sim_debug (DBG_TRC, &sim_con_telnet, "sim_os_ttrun() (__APPLE__)\n");

if (!isatty (STDIN_FILENO))                           /* skip if !tty */
    return SCPE_OK;
runtty.c_cc[VINTR] = sim_int_char;                      /* in case changed */
#if (defined(__GNUC__) && !defined(__OPTIMIZE__))       /* Debug build? */
if (sim_dbg_int_char == 0)
    sim_dbg_int_char = sim_int_char + 1;
runtty.c_cc[VINTR] = sim_dbg_int_char;                  /* let debugger get SIGINT with next highest char */
if (!sigint_message_issued) {
    char sigint_name[8];

    if (isprint(sim_dbg_int_char&0xFF))
        sprintf(sigint_name, "'%c'", sim_dbg_int_char&0xFF);
    else
        if (sim_dbg_int_char <= 26)
            sprintf(sigint_name, "^%c", '@' + (sim_dbg_int_char&0xFF));
        else
            sprintf(sigint_name, "'\\%03o'", sim_dbg_int_char&0xFF);
    sigint_message_issued = TRUE;
    sim_messagef (SCPE_OK, "SIGINT will be delivered to your debugger when the %s character is entered\n", sigint_name);
    }
#endif
if (tcsetattr (STDIN_FILENO, TCSANOW, &runtty) < 0)
    return SCPE_TTIERR;
sim_os_set_thread_priority (PRIORITY_BELOW_NORMAL);     /* try to lower pri */
return SCPE_OK;
}

static t_stat sim_os_ttcmd (void)
{
sim_debug (DBG_TRC, &sim_con_telnet, "sim_os_ttcmd() (__APPLE__)\n");

if (!isatty (STDIN_FILENO))                           /* skip if !tty */
    return SCPE_OK;
sim_os_set_thread_priority (PRIORITY_NORMAL);           /* try to raise pri */
if (tcsetattr (STDIN_FILENO, TCSANOW, &cmdtty) < 0)
    return SCPE_TTIERR;
return SCPE_OK;
}

static t_stat sim_os_ttclose (void)
{
return sim_ttcmd ();
}

static t_bool sim_os_ttisatty (void)
{
return isatty (STDIN_FILENO);
}

static t_stat sim_os_poll_kbd (void)
{
int status = 0;
unsigned char buf[1];

sim_debug (DBG_TRC, &sim_con_telnet, "sim_os_poll_kbd() (__APPLE__)\n");

if (sim_os_poll_kbd_ready(0))
    status = read (STDIN_FILENO, buf, 1);
if (status != 1)
    return SCPE_OK;
if (sim_brk_char && (buf[0] == sim_brk_char))
    return SCPE_BREAK;
if (sim_int_char && (buf[0] == sim_int_char))
    return SCPE_STOP;
return (buf[0] | SCPE_KFLAG);
}

static t_bool sim_os_poll_kbd_ready (int ms_timeout)
{
fd_set readfds;
struct timeval timeout;

if (!sim_ttisatty()) {                      /* skip if !tty */
    sim_os_ms_sleep (ms_timeout);
    return FALSE;
    }
FD_ZERO (&readfds);
FD_SET (STDIN_FILENO, &readfds);
timeout.tv_sec = (ms_timeout*1000)/1000000;
timeout.tv_usec = (ms_timeout*1000)%1000000;
return (1 == select (1, &readfds, NULL, NULL, &timeout));
}

static t_stat sim_os_putchar (int32 out)
{
char c;

c = out;
if (write (STDOUT_FILENO, &c, 1) != 1)
    return SCPE_IOERR;
return SCPE_OK;
}

/* End of __APPLE__ */
```

**Comment by markpizz** [comment]
If the altairz80 was the only simulator that folks intended to use on macOS, your blocking I/O on the console port would be a reasonable solution.  Many/most other simulators will have negative timing effects if this I/O was blocking.

The altairz80 simulator has various timing issues due to the direct use of sim_os_ms_sleep() so it theoretically is innately immune to the timing consequences that the blocking I/O entails.

**Comment by markpizz** [comment]
> After fixing the typos I ran the above program (the version with "write" not "fwrite") on the latest macOS Catalina (macOS 10.15.7 (19H15)) and let it produce two million lines of output, all fine. So I am not yet convinced that there is a macOS bug. Actually the use of "write" instead of "fwrite" might open up a route to fix the problem as error handling for "write" appears to be possible while for "fwrite" I do not see a reliable way once a problem has occurred.

Hmm... What type of window are you running the test program in?  I've been using the macOS "Terminal" application.  Is it possible that this application is getting data too fast and creating the problem we're seeing?

> Also note that Patrick's original test program will also stop on Ubuntu 20.10 with the message (in my case):
bytes=109, lines=160, *errno=11, err_msg="Resource temporarily unavailable"
This means that the issue when lots of debug data is written to stdout will most likely happen there as well. Of course I fully agree with your suggestion to dump this much data to a file and take it from there.

I just committed a change which will retry incomplete debug output writes as needed to get all the output delivered.  Anyone blowing large amounts of debug data out stdout or stderr certainly isn't interested in subtle timing effects which may happen when that is going on.  In fact, even writing debug data to a file significantly effects timing - I've got some unsolved timing problems which the are effected by Heisenberg effect...

**Comment by deltecent** [comment]
>The altairz80 simulator has various timing issues due to the direct use of sim_os_ms_sleep() so it theoretically is innately immune to the timing consequences that the blocking I/O entails.

So I'm clear, you're saying calling sim_os_ms_sleep(10) within the instruction path is causing the Execution Rate calculation to change from 280,000 instructions per second to 16,371,100 instructions per second (a factor of 60), although the simulator is still processing instructions at an approximate rate of 280,000 per second, and there couldn't possibly, under any circumstances, be a bug in sim_timer somewhere? If that's the case, I will refocus my efforts on the instruction loop in the simulator.
```
sim> show clock
Minimum Host Sleep Time:        1 ms (1000Hz)
Host Clock Resolution:          1 ms
Execution Rate:                 16,371,100 instructions/sec
Calibrated Timer:               Internal Timer
Catchup Ticks:                  Disabled
Pre-Calibration Estimated Rate: 5,000,000
Calibration:                    Always
Asynchronous Clocks:            Available
Time at sim> prompt:            9:33:49.339 hours

Altair 8800 (Z80) clock device is Internal Calibrated Timer(INT-TIMER)
Calibrated Timer 8:
  Running at:                100 Hz
  Tick Size:                 
  Ticks in current second:   14
  Seconds Running:           5,006 (1:23:26 hours)
  Calibration Opportunities: 5,006
  Instruction Time:          1444683203
  Real Time:                 3433627528
  Virtual Time:              3433628067
  Next Interval:             1,500
  Base Tick Delay:           109,141
  Initial Insts Per Tick:    50,000
  Current Insts Per Tick:    163,711
  Initializations:           2
  Ticks:                     500,613
  Initialize Base Time:      21:10:02.748
  Wall Clock Time Now:       08:07:26.070
```

**Comment by markpizz** [comment]
I'm explicitly saying that calling sim_os_ms_sleep() in the instruction execution path will absolutely interfere with sane clock calibration.  Doing so is not going to be something which will be supported.  Trying to solve potential calibration issues while allowing sim_os_ms_sleep() to be called is a head banging against the wall exercise.  Feel free to do it if helps you sleep at night. :-)

**Comment by markpizz** [comment]
Back in issue system after using @psco's explicit attach test_write.c and test_fwrite.c attachments

On Sunday, November 15, 2020 at 7:46 AM, Peter Schorn wrote:
> for more clarity and precision I have included the two test programs I
> ran on my macOS Catalina in the macOS Terminal system with my
> assessment:
> 
> 1. In macOS terminal
> gcc test_fwrite.c -o test_fwrite
> ./test_fwrite
> 
> Basically this uses fwrite():
> 
> void fwrite_it (const char *buf, size_t len, FILE *f)
> {
>      while (len > 0) {
>        written = fwrite (buf, 1, len, f);
>        if (written >= 0) {
>          len -= written;
>          buf += written;
>        }
>        errno = 0;
>      }
> }
> 
> 
> This will create incorrect output such as
> (0000098) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
> (0000099) 0123456789012345678901234567890123456789012345(0000099) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
> (0000100) 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
> 
> In my opinion this is due to the fact that when fwrite() indicates the
> error condition (i.e. written < len) there is basically not much what
> can be done any more to recover in all such cases. I can't find anything
> in the specification of fwrite() which clearly spells out what can /
> should be done next when an error occurs. As demonstrated on macOS the
> obvious approach, namely to retry, does not work.

Hmm...

fwrite() is specifically defined to return a size_t value (NOT the ssize_t that write() 
is defined with).  So, in any case where the returned value is < len a correct retry 
for any remaining data should be possible (this certainly should be possible given
what is being written are bytes rather than bigger objects).  I theorized that maybe
error state in the FILE* object was interfering with some of this, so I changed the 
fwrite() case to:

ssize_t written;
int errors = 0;

void fwrite_it (const char *buf, size_t len, FILE *f)
{
    while (len > 0) {
      written = fwrite (buf, 1, len, f);
      if (written >= 0) {
        len -= written;
        buf += written;
      }
      if (errno != 0) {
          ++errors;
          clearerr(f);
          errno = 0;
          }
    }
}

That didn't change anything.

There are several reasons I don't want to change that explicitly to use write().
1) other activities throughout SCP reference stdout either explicitly or implicitly 
and jumping behind the C runtime's buffering may produce other inconsistent 
behavior.
2) write() is not a system call on Windows, and although the Windows C runtime
defines an entry point with this name, the function signature has it returning an 
int without any definition for ssize_t.

Notice that the above code counts the times errno is not 0.  There are MANY of 
these cases, and on Linux the test behaves correctly with either fwrite() or write().

> 2. In macOS terminal
> gcc test_write.c -o test_write
> ./test_write
> 
> Basically this uses write():
> 
> void fwrite_it (const char *buf, size_t len, FILE *f)
> {
>      int fd = fileno(f);
> 
>      while (len > 0) {
>        written = write (fd, buf, len);
>        if (written >= 0) {
>          len -= written;
>          buf += written;
>        }
>        errno = 0;
>      }
> }
> 
> This returns 2'000'000 lines of correct output (it is a bit awkward to
> copy/paste from Terminal to a text editor for comparison purposes but it
> works). I believe this positive result is primarily due to the better
> post-condition after a partial write: Basically the documentation
> encourages one to try again with what has not yet been written and this
> works.
> 
> In summary I think, the version based on write() should be ok while the
> version based on fwrite() can still fail.

In the case that we're using it (writing bytes), the fact that it doesn't 
return the number actually written is really a bug on macOS's C runtime.
Merely returning the write return value when it is >= 0 and setting errno 
(or not) would be good and returning 0 and definitely setting errno if 
write returned -1.

The behavior I'm suggesting here conforms to the relevant documentation 
for both write() and fwrite(), doesn't it?

- Mark

**Comment by psco** [comment]
Unfortunately the problem is not solved on macOS with this [commit](https://github.com/simh/simh/commit/ba5e18e9633b9f8e62f1d4ba98afc4bc1b279ad6), large debug output may still be incomplete.

Looking at the specification for fwrite() (e.g. see [here](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/fread.3.html)) and in particular this section:

> RETURN VALUES
>      The functions fread() and fwrite() advance the file position indicator
>      for the stream by the number of bytes read or written.  They return the
>      number of objects read or written.  If an error occurs, or the end-of-
>      file is reached, the return value is a short object count (or zero).
>      The function fread() does not distinguish between end-of-file and error;
>      callers must use feof(3) and ferror(3) to determine which occurred.  The
>      function fwrite() returns a value less than nitems only if a write error
>      has occurred.

When it comes to error conditions for fwrite(), the only thing we have is the last sentence: If and only if the return value is less than nitems, we have an error. I am pretty sure that macOS indicates quite correctly when this condition occurs for the first time. The problem is that the specification leaves it open how to recover from this situation and makes no promises at all. Of course it would be nice if continuing with the not-written elements (as implemented in _debug_fwrite_all()) could handle the write error but unfortunately this is just an assumption which is not true on macOS. In fact, continuing to call fwrite() just loses output.

**Comment by markpizz** [comment]
> The problem is that the specification leaves it open how to recover from this situation and makes no promises at all. Of course it would be nice if continuing with the not-written elements (as implemented in _debug_fwrite_all()) could handle the write error but unfortunately this is just an assumption which is not true on macOS. In fact, continuing to call fwrite() just loses output.

Actually, from what I've seen, it doesn't seem to lose output.  Sometimes it emits some of the output that originally was written and then can complete the whole thing since it always returns 0 on any error, so the retry is for the whole buffer again.

The spec may be a little weak, but it would be nice if it behaved in a more useful way (as things do on other platforms).

For simulators which don't call sim_os_ms_sleep() during instruction execution, the "occasional buffered file flush facility" which previously always flushed every 30 seconds now just been enhanced to expose a REGister that can influence the interval that buffered files are flushed:

```
sim> DEPOSIT FLUSH_INTERVAL 1
```

will cause a fflush(sim_deb) every second.  Since this mechanism depends on sim_activate_after working, I make no guarantees about how this will work with a simulator that calls sim_os_ms_sleep().

This "should" help an external "tail -f debug.file" produce something useful...

**Comment by deltecent** [comment]
I'm finding all these timing functions just shy of incomprehensible, so if `sim_os_ms_sleep()` is going to be removed from `sim_instr_mmu()` and the "set sio sleep" stuff, it's going to have to be done by either @psco or @markpizz.

Regarding the use of non-blocking sockets, we'll just have to agree to disagree on that I'll maintain my sim_console `__APPLE__` code block in my own fork.

Thank you both for looking into this. I hope something useful comes out of it.

**Comment by markpizz** [comment]
> Regarding the use of non-blocking sockets, we'll just have to agree to disagree on that I'll maintain my sim_console __APPLE__ code block in my own fork.

Have you tried the latest writing the debug output to a file and using "tail -f debug.file" after starting your configuration with DEPOSIT FLUSH_INTERVAL 1?

**Comment by markpizz** [comment]
@psco said: Unfortunately the problem is not solved on macOS with this commit, large debug output may still be incomplete.

It may not be solved now (some extra output is produced), but it is the right answer for all platforms which have well behaved fwrite() return values.  Previously it merely would drop all sorts of debug output data.  Now you get a little extra junk on macOS until the underlying C runtime is improved.  We can live with some extra "junk" in the debug output easily enough when producing prodigious amounts of it.

**Comment by psco** [comment]
Actually the current version on macOS does not produce extra output in my examples, it just drops output now and then as before. Same goes for Ubuntu where the amount of dropped output can be huge. Two examples:

Example on Ubuntu 20.10

Expected output
...
DBG(443346)> DSK IN: DSK0: [0x0000f60f] IN 0x09
DBG(443352)> DSK IN: DSK0: [0x0000f60f] IN 0x09
plus around 500 more lines, not all the same btw
DBG(495092)> DSK IN: DSK0: [0x0000f60f] IN 0x09
...

Output seen in terminal window
...
DBG(443346)> DSK IN: DDBG(495089)> DSK IN: DSK0: [0x0000f60f] IN 0x09
DBG(495092)> DSK IN: DSK0: [0x0000f60f] IN 0x09
...
Note that the behavior on Ubuntu is quite non-deterministic. I have even seen a fully correct output in the terminal window but when things go wrong then lots of lines get dropped.


Example on macOS 10.15.7 (19H15)

Expected output
...
DBG(29452)> DSK IN: DSK0: [0x00005c2d] IN 0x09
DBG(29455)> DSK IN: DSK0: [0x00005c2d] IN 0x09
DBG(29464)> DSK READ: DSK0: [0x00005c3f] IN 0x0a (READ) D0 T0 S7
...

Output seen in terminal window
...
DBG(29452)> DSK IN: DSK0: [0x00005c2d] IN 0x09
DBG(29455)
DBG(29464)> DSK READ: DSK0: [0x00005c3f] IN 0x0a (READ) D0 T0 S7
...

**Comment by markpizz** [comment]
@pcsco, Thanks for clarifying my mistaken impression.  

After some additional testing with the external test programs here, I think I've got a well behaved result in the next commit.

**Comment by psco** [comment]
This looks much better - I get only some extra empty lines on macOS for my test case which is ok. Maybe it would make sense to rewrite the while-loop in *_debug_fwrite_all* to:

```
while (len > 0) {
    len_written = fwrite (buf, 1, len, f);
    if (len_written < len)    /* Non blocking file descriptor buffer full? */
        sim_os_ms_sleep(10);  /* wait a bit to retry */
    len -= len_written;
    buf += len_written;
    }
```

This would remove the reference to *errno* where I am not really sure that *fwrite()* is obliged to set it (although it obviously does). The condition `len_written < len` (i.e. a write error occurred) is definitely also a reason (probably the same reason as `errno == EAGAIN`) to give the system a little rest before retrying. On macOS a version of *_debug_fwrite_all* with the while-loop from above gives me basically the same terminal output for my test case, i.e. the expected output with some extra empty lines.

**Comment by markpizz** [comment]
I think errno needs to be cleared since something else may check it later.  Not every C runtime function clears it on success, but sets it on failure.  Not all callers of functions which can set errno, clear it before calling the relevant function...

Also, I'm pretty sure that I've seen errno set when the full buffer was written already.

**Comment by markpizz** [comment]
No debug data is being lost anymore, so I'm closing this issue.

**Comment by Rhialto** [comment]
On Sun 15 Nov 2020 at 11:57:55 -0800, Mark Pizzolato wrote:
> ssize_t written;
> int errors = 0;
> 
> void fwrite_it (const char *buf, size_t len, FILE *f)
> {
>     while (len > 0) {
>       written = fwrite (buf, 1, len, f);
>       if (written >= 0) {
>         len -= written;
>         buf += written;
>       }
>       if (errno != 0) {
>           ++errors;
>           clearerr(f);
>           errno = 0;
>           }
>     }
> }

A (potential) problem with this code would be that errno is inspected in
cases where it shouldn't be. Errno is set when an error occurs, yes, but
it isn't cleared when no error occurs. Generally it is recommended to
look at errno only if a function (that has been documented to set errno)
returns an error indicator. Preventively resetting errno beforehand
probably also works (such as before calling fwrite()), but I don't
recall if that's supposed to be officially sanctioned.

**Comment by markpizz** [comment]
The current code "may" cause code which:
1) does something which sets errno
2) emits debug output BEFORE  checking errno
3) then checks errno

Fortunately, essentially no normal code paths through simulator instruction execution OR simulated DEVICE activity explicitly references errno.  These are the interesting places where debug output will be emitted.

**Comment by markpizz** [comment]
@Rhialto was right about the potential errno issue, hence I vaguely remembered his point and was able to address #1108 quickly.  The solution to #1108 was to explicitly clear errno prior to the fwrite() which was essentially the only choice since fwrite() doesn't return an error status.  I dug through the rest of the simh codebase and errno is always only being referenced otherwise when an error value was returned from a system call.
